---
#Database details
db_host: "localhost"
db_port: "3306"
db_name: "max_music_data"
db_user: "max_ingestor"
db_password: "Zv2MGcoR)KpIq#oEgF9]"

#File characteristics
field_delimiter: "\u0001"
row_delimiter: "\u0002"  # The script contains handling for the "\n" character in each row delimiter
comment_char: "#"

#Inboxes for file ingestion
ready_path: "./import/ready/"
finished_path: "./import/finished/"
failed_path: "./import/failed/"

logger_config_path: "./logger.conf"