---
db_info:
  db_host: "localhost"
  db_port: "3306"
  db_name: "max_music_data"
  db_user: "max_ingestor"
  db_password: "Zv2MGcoR)KpIq#oEgF9]"
  log_sql_statements: True

file_structure:
  field_delimiter: "\u0001"
  row_delimiter: "\u0002"  # The script contains handling for the "\n" character in each row delimiter
  comment_char: "#"

inboxes:
  ready_path: "./inboxes/ready/"
  finished_path: "./inboxes/finished/"
  failed_path: "./inboxes/failed/"